apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: aws-key
  namespace: earnings-api
spec:
  encryptedData:
    secretAccessKey: AgBHAWJZDrWRtvUNYtiNvwilUu8rHEQ/c0gt9Y6pWczQ9lK03PI/nKP8E4cqMcg999ezS/ceco2wUv5KdCNR24gzAWEaGuJR6mEuU430iKlChu2rwB9U+XGEAK4VGaq0eBEUb0rKOoqWLtETuwvDtT+jlDEYnqeCCrDZPtRf/VIwqBpoCbCJzOCRr/RHG0li7UmqUPm/HxcLtmkn9VB0qNrNCh/EFUutLA+gK2zYslpvdbXo0vqVovrxw3LGwx69i2YKT1RQhGJVGpkDJmYStECDX2kw9sSfFBAG6Z8do7E16Uaqxgpv2uGbIKeCBtIBv367EYBhJtbi6VBhVJu6BdXIKlahcUXz0qa0Snw80jslpC2xTfMaEPPH89u6zhc3Ip3GdeTM3YBYsjKItQRtwWpxmZd9f+lHraT7HfQrllUMqYFiAH1OIoCc9idmwDD+iZS0mi/a1oBkvVrMbaoVh1b9BsoGi/zFosw0SIYYz/nDBE7IJmZjT5Dp/ugg4hmy6SzFhPlgZWHm3ZmESZh5+FeR/ryLEb2Y8QyvWp7zM6OBSO4zioQTixBxb9Yv47JCBnPYbqjsO+9zQ4PYV76yDFa0Olq8NDcBE2DHBLZfRqj0AQU7+f2+6JYMhLNoxV0vRrZ7kAIcj5Tvdu89fliIW/JiULjre19BncThmYVVxhPaT7swuiWaLPrlwNbuTegUzcpnDrNYSZeFBA==
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: aws-key
      namespace: earnings-api

