apiVersion: apps/v1
kind: Deployment
metadata:
  name: treetracker-earnings-api
  labels:
    app: treetracker-earnings-api
spec:
  template:
    spec:
      containers:
        - name: treetracker-earnings-api
          env:
            - name: S3_ACCESS_KEY_ID
              value: AKIAQYWVSSHAHDJKENBO
            - name: S3_BUCKET
              value: payments-batch-upload-for-prod
