apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: aws-key
  namespace: earnings-api
spec:
  encryptedData:
    secretAccessKey: AgCEnpFiTf2mNZxZQVEE0KRuEnQGJac4ch+cF1eBmLqcHr+Mt0h3t0Y8yCT9WFIdfuLdoSOZ9M34Uuk6rBU/3dw8xNdXOMrwk2jzoUApq+vweEjFVV8Ch89pk7Oe6I2tnJjOTuiQhmlbnpx1RUlM5DrEYe8UnZAPqHpgBNgQKTO7cY4w42POnuQIz2hgAl5eAJGZbDzjQupKADRJqhQXHcBNWXNlkSCN91oZwQh2YuI9vQV8OQL8BfE2ZKcwI2rBK0Nqf4hakpGV+TZuhWrjadKZjBaSun//F8+z4tbtL2m4jfRZe2i5L4+US1jKTjUg2Kjl+LGTglTi7OZq5IlISTBNNLyTPnx3bFKnQy/iNyQ/tZgiu4H6EYg4S60XftQm942Aa/wjM9OjAfOQXklFmYtNRUuO2esr5jejgAwoYN2FJMuuY0HIaZiDA0cTLWO+ULo1x8VgGgDFQdn4nrJw+9pAj71E4GN5o6JMq6dyfG4i9wjP/MFmXpsD5kXQsZ+On0XqROMlTZNGdpRD52IypN71sNBGPFTFjo0xiIUwGPKMuU/xekVGRaIi++t8gp5EYH78x8VsJrQKVAtOQXYNeDeQ0X+4v20EOGvRgT7MyIRFxqjVeh92eQ89AOvxSQffDolSNh/Sgb5kh4xCe5NNeui0rJyKeqc6nZPXnbIrl7GGKz/UC68QG965LSwSBj/QQfsEV82ZVgcNjUbaSAUEQcwZaj0vzJXIR38hiXXZ0DF0frEqjNWHzWrC
  template:
    metadata:
      creationTimestamp: null
      name: aws-key
      namespace: earnings-api
