apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: aws-key
  namespace: earnings-api
spec:
  encryptedData:
    secretAccessKey: AgCX8HOdrRvxK5ht9vIfo6oVg8iSfBA2lmFBFH8COO/llfdKbpiAzcsXUoGIQeEw/bNPFOak5BJSFBSYjWde8jlUfSs2MZnhkLMt4J/EUVW5jHc2TwZsE6iNz2qTfc304EXkAvtlg6M5jT4I2s2k8YITSF8VKbepzNSHlwfrS8DAYULsazPiJRcbRytRo70JtySZZUL5geuKKrNfBllUdGAauHw+d9icWrTt/FonbYvPgy+GBcDc7RWU9czD86amHAaT2nTveyTJy2bVHA4a0hqBAdd8mS5F15JH84+rSXaiw0jevQhQVBQZOBKhconLfB9N3RHFhmY2xYisPh1A+NdWDVDkJouSaW/djT8EBG2Tt/qX/vD0Ky8egeumGTK0AS3Kg8a6eJdOlAP9Ek+ieM5S4Vq2GZleBi9aPodErHWMZPBHGo17nujA0bCayUFuYGf2Ya8M0uW9ckUa5pBqRTzbfOSf9BXS8ap3hDYMBv4+dSqvDjpjTt3jNwMrRNNa/fa3+NYbicnuDBVoQ8pH6W5udVTkwRNDwvWnFqDiu+IrLTINa58IEgabqdLjj337YOfAKEP9CB/MAUJKrMFf+bjLZ2ljW2iRx/wsQMI7JSB6fbcJuqAZjxBOVCaoAhJG1roCYtkHEiXD+zsDzXQ0LoMYrD2Xm8HW4utWx9NwosaTsB3eV8TN8kJO2GdfHSzeb78BiQ+BVfli4A/cmziKtg==
  template:
    metadata:
      creationTimestamp: null
      name: aws-key
      namespace: earnings-api
