name: Test Tool

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'The count of capture'
        required: true

env:
  project-directory: ./

jobs:
  seed:
    name: Generate data to DB
    runs-on: ubuntu-latest
    if: |
      !contains(github.event.head_commit.message, 'skip-ci') &&
      github.event_name == 'push' &&
      github.repository == "Greenstand/${{ github.event.repository.name }}"
    steps:
      - name: Install doctl for kubernetes
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DEV_DIGITALOCEAN_TOKEN }}
      - name: Save DigitalOcean kubeconfig
        run: doctl kubernetes cluster kubeconfig save ${{ secrets.DEV_CLUSTER_NAME }}
      - name: List pods in microservice
        run: kubectl -n ${{ secrets.K8S_NAMESPACE }} get pods
      # - name: Update kubernetes resources
      #   run: kustomize build deployment/overlays/development | kubectl apply -n ${{ secrets.K8S_NAMESPACE }} --wait -f -
      # - name: Attempt to wait for migration job to complete
      #   run: kubectl wait -n ${{ secrets.K8S_NAMESPACE }} --for=condition=complete --timeout=45s job/database-migration-job
